---

# This is the basis of a playbook to deploy Omero on a single standalone server
# This will install and configure all the components.
# The roles listed below will do the real work


- Name: Apply roles
  role:
  - nginx-install
  - postgresql-install
  - omero-server-install
  - omero-web-install

