---
# tasks file for icr-omero-firewalld
# always do port 22

- name: ssh firewall service
  firewalld:
    service: ssh
    permanent: yes
    state: enabled

- name: http firewall service 
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: httpsfirewall service 
  firewalld:
    service: https
    permanent: yes
    state: enabled

- name: ldap firewall service 
  firewalld:
    service: ldap
    permanent: yes
    state: enabled

- name: ldaps firewall service 
  firewalld:
    service: ldaps
    permanent: yes
    state: enabled

- name: ice ports
  firewalld:
    port: 4063/tcp 
    permanent: yes
    state: enabled

- name: ice ports
  firewalld:
    port: 4064/tcp 
    permanent: yes
    state: enabled

